import type {Metadata} from "next";
import localFont from "next/font/local";
import "./../styles/globals.css";
import "./../styles/fonts.css";
import FullNavBar from "./components/organisms/fullNavBar";
import {Footer} from "./components/organisms/footer";

const geistSans = localFont({
	src: "./../assets/fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./../assets/fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

const gothamLight = localFont({
	src: "./../assets/fonts/gotham/Gotham-Light.otf",
	variable: "--font-gotham-light",
	weight: "300",
	style: "normal",
});

const gothamMedium = localFont({
	src: "./../assets/fonts/gotham/Gotham-Medium.otf",
	variable: "--font-gotham-medium",
	weight: "400",
	style: "normal",
});

const gothamBold = localFont({
	src: "./../assets/fonts/gotham/Gotham-Bold.otf",
	variable: "--font-gotham-bold",
	weight: "800",
	style: "normal",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable}
        ${gothamLight.variable} ${gothamMedium.variable} ${gothamBold.variable}
        antialiased`}
			>
				<FullNavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
